class destination{
  constructor(){
    this.w=width/3;
    this.l=height/3;
    this.r=40;
  }
  display(){
    stroke(0);
    fill(60,220,240);
    rect(this.w,0,this.w,this.r);
    rect(0,this.l,this.r,this.l);
    rect(this.w,height-this.r,this.w,this.r);
    rect(width,this.l,-this.r,this.l);
    
    text("North",width/2-8,this.r/2);
    text("West",this.r/2-18,height/2);
    text("East",width-(this.r)/2-20,height/2);
    text("South",width/2-8,height-this.r/2);
    
    beginShape();
    vertex(0,0);
    vertex(this.w,0);
    vertex(this.w,this.r);
    vertex(this.r,this.r);
    vertex(this.r,this.l);
    vertex(0,this.l);
    endShape();
    beginShape();
    vertex(0,2*this.l);
    vertex(this.r,2*this.l);
    vertex(this.r,height-this.r);
    vertex(this.w,height-this.r);
    vertex(this.w,height);
    vertex(0,height);
    endShape();
    beginShape();
    vertex(2*this.w,height);
    vertex(2*this.w,height-this.r);
    vertex(width-this.r,height-this.r);
    vertex(width-this.r,2*this.l);
    vertex(width,2*this.l);
    vertex(width,height);
    endShape();
    beginShape();
    vertex(2*this.w,0);
    vertex(width,0);
    vertex(width,this.l);
    vertex(width-this.r,this.l);
    vertex(width-this.r,this.r);
    vertex(2*this.w,this.r);
    endShape();
  }
  update(){
    this.display();
  }
}
